name: Build YOJ (unit tests only)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  build:
    name: Build YOJ (unit tests only)
    runs-on: ubuntu-latest

    env:
      MAVEN_ARGS: --batch-mode --update-snapshots -Dstyle.color=always

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore

      - name: Build with Maven
        run: mvn $MAVEN_ARGS verify

      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save
